# v2 应用代码修改，再次update，install
FROM 10.10.10.10:5002/openwrt-build:v1

USER opde:opde
ENV HOME /home/opde

WORKDIR /openwrt/lede

# 使用diy-script.sh添加软件包
COPY diy-script.sh /openwrt/lede
RUN sudo chown opde:opde /openwrt/lede/diy-script.sh
RUN bash /openwrt/lede/diy-script.sh

# 修改默认ip为 10.10.10.254
RUN sed -i 's/192.168.1.1/10.10.10.254/g' package/base-files/files/bin/config_generate
# 时区
RUN sed -i "s/'UTC'/'CST-8'\n   set system.@system[-1].zonename='Asia\/Shanghai'/g" package/base-files/files/bin/config_generate


RUN rm -rf /openwrt/lede/diy-script.sh

RUN ./scripts/feeds update -a 

RUN ./scripts/feeds install -a

# TTYD 免登录
RUN sed -i 's|/bin/login|/bin/login -f root|g' feeds/packages/utils/ttyd/files/ttyd.config
