# v1 clone代码，并执行基础的的update与install
FROM 10.10.10.10:5002/openwrt-build:base

USER opde:opde
ENV HOME /home/opde

WORKDIR /openwrt

RUN git clone https://github.com/coolsnowwolf/lede

WORKDIR /openwrt/lede

RUN ./scripts/feeds update -a 

RUN ./scripts/feeds install -a


