# v3 复制config，并下载依赖
FROM 10.10.10.10:5002/openwrt-build:v2

USER opde:opde
ENV HOME /home/opde

WORKDIR /openwrt/lede

COPY config_1 /openwrt/lede/.config
RUN sudo chown opde:opde /openwrt/lede/.config
RUN make defconfig

RUN make download -j$(nproc)

# 这里我是本地编译
# RUN make V=s -j$(nproc)